"""empty message

Revision ID: 4d1e2222850d
Revises: 
Create Date: 2023-04-02 10:34:31.459331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1e2222850d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('numId', sa.String(length=5), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=15), nullable=True),
    sa.Column('prenom', sa.String(length=25), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('numId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('telephone', sa.String(length=8), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=50), nullable=False),
    sa.Column('qteStock', sa.Integer(), nullable=False),
    sa.Column('prixUnit', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateCom', sa.DateTime(), nullable=False),
    sa.Column('qteProd', sa.Integer(), nullable=False),
    sa.Column('produitId', sa.Integer(), nullable=False),
    sa.Column('clientId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clientId'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['produitId'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livraisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateLiv', sa.DateTime(), nullable=False),
    sa.Column('qteLiv', sa.Integer(), nullable=False),
    sa.Column('agentId', sa.String(length=5), nullable=False),
    sa.Column('commandeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agentId'], ['agents.numId'], ),
    sa.ForeignKeyConstraint(['commandeId'], ['commandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livraisons')
    op.drop_table('commandes')
    op.drop_table('produits')
    op.drop_table('clients')
    op.drop_table('agents')
    # ### end Alembic commands ###
